sudo: false


language: python
python:
  - "2.7"
 # - "3.6"

install:
  - pip install codecov

env:
  - CODECOV_TOKEN="754ec358-2c9e-4f15-8123-b44041c1f09b"
script:
  - coverage run test.py

after_success:
  - codecov