sudo: false

language: python
python:
  - "2.7"
  - "3.6"
  # - "3.7"  fails build 'Unable to download 3.7 archive. The archive may not exist.''

notifications:
  email: never

install:
  - pip install codecov
  - pip install pytest
  - pip install pytest pytest-cov
  - pip install pylint

#virtualenv:
#  system_site_packages: true

env:
  - CODECOV_TOKEN="754ec358-2c9e-4f15-8123-b44041c1f09b"  #get token from https://codecov.io/

script:
  - py.test --cov-report xml 
  - coverage run test_script.py
  - pylint test_script.py

after_success:
  - codecov   # go to https://codecov.io/ to see report (have to log in with github)
  #- codecov -t the_repository_upload_token #for private repository
  