sudo: false

language: python
python:
  # - "2.7"
  - "3.6"
  - "3.7-dev"

notifications:
  email: never

install:
  - make install

env:
  - make token

script:
  - make all

after_success:
  - make codecov-public

  # - codecov   # go to https://codecov.io/ to see report (have to log in with github)
  # #- codecov -t the_repository_upload_token #for private repository
  