sudo: false
language: python
python:
- '3.6'
- 3.7-dev
notifications:
  email: never
install:
- make install

script:
- python save.py

deploy:
  provider: script
  skip-cleanup: true
  script: bash .travis/push.sh $GH
  on:
    branch: master

# after_success:
# - codecov
